PACKAGE_NAME="snd-roland-mc707"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="snd-roland-mc707"
DEST_MODULE_LOCATION[0]="/updates"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build modules"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"

AUTOINSTALL="yes"
